id: A75A5FD55
title: 'Bestowing the Splendour of All That is Desirable: Fire Offering for the ''Neck-Pouch
  Dagger’ (Purba Gulkhukma) Cycle'
type: translation
pechas:
- IB871A7F0
- I24C5B722
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:54:34.099388
  last_modified_at: 2023-01-04 11:54:34.099401
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  IB871A7F0/0E0D: CE99
  I24C5B722/D8C6: CE99
